### ISSUE TITLE
Update the phone number in the bottom of the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YoshithaRathnayake#231]
**Is your feature request related to a problem? Please describe.**
Currently, there is a wrong phone number

**Describe the solution you'd like**
Add my new phone number as +94 72 825 9003

**Are you work on this?**
No

**Comment by Vaishnavi-More** [comment]
Hey @YoshithaRathnayake I have updated the phone number. Kindly review my pull request and accept it. I am beginner so kinldy let me know if any changes required.
Thank you!

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake I have updated the phone number. Kindly review my pull request and accept it. I am beginner so kindly let me know if any changes required. Thank you!

Sure go ahead @Vaishnavi-More

**Comment by Vaishnavi-More** [comment]
> > Hey @YoshithaRathnayake I have updated the phone number. Kindly review my pull request and accept it. I am beginner so kindly let me know if any changes required. Thank you!
> 
> Sure go ahead @Vaishnavi-More

Actually I have send you the pull request by updating the read me file kindly review my request and accept my PR!
Thank You!

**Comment by YoshithaRathnayake** [comment]
> > > Hey @YoshithaRathnayake I have updated the phone number. Kindly review my pull request and accept it. I am beginner so kindly let me know if any changes required. Thank you!
> > 
> > 
> > Sure go ahead @Vaishnavi-More
> 
> Actually I have send you the pull request by updating the read me file kindly review my request and accept my PR! Thank You!

Changes requested no didn't you see it @Vaishnavi-More

**Comment by Vaishnavi-More** [comment]
@YoshithaRathnayake Please will you let me know which screenshot I have to remove? Actually I am beginner and I am not getting it. Kindly guide me if possible.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Please will you let me know which screenshot I have to remove? Actually I am beginner and I am not getting it. Kindly guide me if possible.

No no you don't do anything I will do @Vaishnavi-More ok?
