### ISSUE TITLE
Change the LinkedIn link

### ISSUE THREAD

**Issue by george0st** [YoshithaRathnayake/YoshithaRathnayake#372]
**Describe the bug**
The web page contain this link 'https://www.linkedin.com/in/yoshitha-rathnayake' but it return 'https://www.linkedin.com/404/' it means 'This page does not exist.'

**Comment by YoshithaRathnayake** [comment]
Yeah, thank you for finding this issue I think my linkedin account has deleted. So I'll make a new account and let u know @george0st

**Comment by YoshithaRathnayake** [comment]
> **Describe the bug** The web page contain this link 'https://www.linkedin.com/in/yoshitha-rathnayake' but it return 'https://www.linkedin.com/404/' it means 'This page does not exist.'

https://www.linkedin.com/in/YoshithaRathnayake

@george0st you can replace this link with the old link. You can work on this!

**Comment by YoshithaRathnayake** [comment]
@george0st Any updates? Aren't you working on this?

**Comment by george0st** [comment]
The link works, thx

**Comment by YoshithaRathnayake** [comment]
No its not bro @george0st I changed my linkedin account

**Comment by YoshithaRathnayake** [comment]
This is my repo bro I'll decide it should be closed or not @george0st
