### ISSUE TITLE
Add the youtube logo to the contact me section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YoshithaRathnayake#397]
**Is your feature request related to a problem? Please describe.**
Currently, the youtube logo and my channel is not there in the contact me section

**Describe the solution you'd like**
Add the youtube logo and the link my channel to that logo
Channel link :- https://www.youtube.com/channel/UCiuDD_uA4v5PF2cr-3nTChA

**Describe alternatives you've considered**
Don't forget to subscribe my channel 🔥

**Are you work on this?**
No

**Comment by ad-astra-per-ardua** [comment]
Can i take this issue?

**Comment by YoshithaRathnayake** [comment]
> Can i take this issue?

Yeah sure @ad-astra-per-ardua

**Comment by YoshithaRathnayake** [comment]
> Can i take this issue?

@ad-astra-per-ardua Any updates? Aren't you working on this?
