### ISSUE TITLE
Change the LinkedIn link

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/YoshithaRathnayake#400]
**Is your feature request related to a problem? Please describe.**
Currently, I have changed my linkedin account and in the readme.md file its the wrong link

**Describe the solution you'd like**
Change the LinkedIn link

New link :- https://www.linkedin.com/in/YoshithaRathnayake

**Are you work on this?**
No

**Comment by Achal-00** [comment]
Hey, I'd like to work on this.

**Comment by YoshithaRathnayake** [comment]
> Hey, I'd like to work on this.

Yeah sure, go ahead @Achal-00

**Comment by YoshithaRathnayake** [comment]
Dont forget to follow my account @Achal-00
